### ISSUE TITLE
Entry point jsnext:main does not exist

### ISSUE THREAD

**Issue by luzat** [Val-istar-Guo/koa-csp#1]
`package.json` contains a `"jsnext:main": "src/csp.js"` entry, but `csp.js` does not exist. It's likely that it should ...

1. refer to `src/index.js`
2. be replaced by `module: "src/index.js"` (see e.g. this [rollup issue](https://github.com/rollup/rollup/issues/969))

In practice the wrong `jsnext:main` entry leads to `eslint-plugin-import` returning an `import/no-unresolved`  error and a linting failure, but using either `module` or `jsnext:main` with `src/index.js` works.

**Comment by Val-istar-Guo** [comment]
thanks for report
