### ISSUE TITLE
Bug: When are you writing "yarn install" to get  Command failed: "is-ci || husky install" 

### ISSUE THREAD

**Issue by hasot** [Val-istar-Guo/koa-csp#11]
I write yarn install and this package don't work without '--ignore-scripts'. What could i do for install without ignore scripts 
<img width="414" alt="image" src="https://user-images.githubusercontent.com/9951916/227228595-c2c116e0-1dc3-4568-8f24-c740e091bac8.png">

**Comment by Val-istar-Guo** [comment]
https://github.com/Val-istar-Guo/koa-csp/commit/b8d001efaf10112ac99b81790662bc880b494a2a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L28

fixed, install 1.2.1
