### ISSUE TITLE
Bug: [kpa-csp warn] Invalid Policy Name: form-action, report-uri

### ISSUE THREAD

**Issue by HasanCanUgurlu** [Val-istar-Guo/koa-csp#13]
**Describe the bug**
Getting `[kpa-csp warn] Invalid Policy Name: form-action, report-uri` on the logs.

**To Reproduce**
add form-action and report-uri policies.

**Additional context**
form-action and report-uri are valid policies for CSP. Please add them in the package. Also is `kpa-csp` a typo?

**Comment by Val-istar-Guo** [comment]
Nice to receive your Pull Request， This issue has been fixed in version 1.2.2
