### ISSUE TITLE
Bug: csp is not a function

### ISSUE THREAD

**Issue by evert** [Val-istar-Guo/koa-csp#18]
**Describe the bug**

When using the latest version of koaCsp with Typescript, I get the error: "csp is not a function".

**To Reproduce**

```typescript
import Koa from 'koa';
import koaCsp from 'koa-csp';

const app = new Koa();

app.use(koaCsp({}));
```

```
file:///home/evert/src/.../app/dist/app.js:19
    app.use(koaCsp());
            ^

TypeError: koaCsp is not a function
    at default (file:///home/evert/src/.../app/dist/app.js:19:13)
    at file:///home/evert/src/.../app/dist/index.js:17:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.16.0
```

Changing the import to:

```typescript
import koaCsp from 'koa-csp/es/src/index.js';
```

emits this error:

```
(node:33735) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33735) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/home/evert/src/sproutfamily/app/node_modules/koa-csp/es/src/index.js:1
import validatePolicy from './validate-policy';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.16.0
```

Some suggested changes (not sure if this is comprehensive):

* `package.json` should have a `exports` key.
* The `es/src` directory should have a minimal `package.json` file with just this key: `{"type":"module"}`.

This should fix both problems.

### Workaround:

```typescript
import koaCspImport from 'koa-csp/lib/src/index.js';
const koaCsp = (koaCspImport as any).default as typeof koaCspImport;
```

**Comment by Val-istar-Guo** [comment]
I modified the build script to use the latest version of typescript, and I'm guessing this should fix the issue you're having.

`type":"module` I don't think it is necessary, because I have set `module": "dist/esm/src/index.js"` in package.json.
I don't think it's necessary to introduce a tool to build minimal package.json.

Upgrade to `koa-csp@1.2.4` and check if this issue still exists.
If you still face this issue, please reopen this issue and provide a example project. I will try to solve this problem.

**Comment by Val-istar-Guo** [comment]
In addition, I have also encountered a special case. in the case,
`import * as koaCsp from 'koa-csp'` seems to solve the problem.

This case seems to be related to the tsconfig.json. If this solves your problem, maybe we need to check tsconfig.json.

**Comment by evert** [comment]
'module' is not a standard key in package.json. exports is the standard.

https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for

If it's helpful, im also a package author and wrote this specifically for supporting both esm and cjs:

https://evertpot.com/universal-commonjs-esm-typescript-packages/

Im definitely not suggesting adding more build tools but there's some flaws in the esm build that suggest to me that this is simply not tested.

I doubt upgrading typescript will do anything here but happy to give it another test later today.

**Comment by Val-istar-Guo** [comment]
The information you provided is very helpful to me. I had no idea that the `module: ` is not standard.
I will fix this issue as soon as possible

**Comment by Val-istar-Guo** [comment]
version 1.2.6 released. 
[universal-commonjs-esm-typescript-packages](https://evertpot.com/universal-commonjs-esm-typescript-packages/) was very helpful.

**Comment by evert** [comment]
Awesome! Works perfectly now. Glad my article also helped. Cheers.
