### ISSUE TITLE
Should this be an async middleware?

### ISSUE THREAD

**Issue by jdrydn** [Val-istar-Guo/koa-csp#5]
Hi there,

Looking at adding a CSP header to my Koa project, and looking at the source here:

https://github.com/Val-istar-Guo/koa-csp/blob/d59f9d6cbd41d405dc06b84abed885c8165471bb/src/index.js#L34-L42

Can't help but think the `async` is redundant if `await next();` is changed to `return next();` as I've seen for other Koa middleware.

So instead:

```js
return (ctx, next) => { 
   if (enableWarn) validatePolicy(policy); 
  
   const policyStr = formatPolicy(policy) 
     .map(directive => directive.join(' ')) 
     .join(';') 
  
   ctx.set('Content-Security-Policy', policyStr); 
   return next();
};
```

I would happily implement this & open a PR, however after quickly looking through tests it would fundamentally change all tests!

**Comment by Val-istar-Guo** [comment]
Thanks for your report.

Using `async` is just a habit of writing koa middleware.
